#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

DEV_VARS="$REPO_ROOT/packages/control-plane/.dev.vars"
WEB_ENV="$REPO_ROOT/packages/web/.env.local"

if [[ -f "$DEV_VARS" && -f "$WEB_ENV" ]]; then
  echo "[bootstrap] .dev.vars and .env.local already exist — nothing to do."
  exit 0
fi

# Generate fresh values. INTERNAL_CALLBACK_SECRET must match across both files,
# so if one file already exists, reuse its value when writing the other.
TOKEN_ENCRYPTION_KEY="$(openssl rand -base64 32)"
REPO_SECRETS_ENCRYPTION_KEY="$(openssl rand -base64 32)"
INTERNAL_CALLBACK_SECRET="$(openssl rand -hex 32)"
LOCAL_DOCKER_DAEMON_SECRET="$(openssl rand -hex 32)"
NEXTAUTH_SECRET="$(openssl rand -base64 32)"

read_existing() {
  local file="$1" key="$2"
  [[ -f "$file" ]] || return 0
  grep -E "^${key}=" "$file" | head -n 1 | cut -d= -f2- || true
}

if [[ -f "$DEV_VARS" ]]; then
  existing="$(read_existing "$DEV_VARS" INTERNAL_CALLBACK_SECRET)"
  [[ -n "$existing" ]] && INTERNAL_CALLBACK_SECRET="$existing"
elif [[ -f "$WEB_ENV" ]]; then
  existing="$(read_existing "$WEB_ENV" INTERNAL_CALLBACK_SECRET)"
  [[ -n "$existing" ]] && INTERNAL_CALLBACK_SECRET="$existing"
fi

if [[ ! -f "$DEV_VARS" ]]; then
  mkdir -p "$(dirname "$DEV_VARS")"
  cat > "$DEV_VARS" <<EOF
# Control plane dev secrets — auto-generated by scripts/dev/bootstrap.sh.
# Do not commit this file. See .dev.vars.example for the template.

TOKEN_ENCRYPTION_KEY=$TOKEN_ENCRYPTION_KEY
REPO_SECRETS_ENCRYPTION_KEY=$REPO_SECRETS_ENCRYPTION_KEY
INTERNAL_CALLBACK_SECRET=$INTERNAL_CALLBACK_SECRET
LOCAL_DOCKER_DAEMON_SECRET=$LOCAL_DOCKER_DAEMON_SECRET

DEPLOYMENT_NAME=local-dev
WORKER_URL=http://localhost:8787
WEB_APP_URL=http://localhost:3000
SCM_PROVIDER=github
SANDBOX_PROVIDER=local-docker
LOG_LEVEL=debug
LOCAL_DOCKER_DAEMON_URL=http://localhost:9000

# Fill these from your dev GitHub App at https://github.com/settings/apps/new.
# The private key MUST be in PKCS#8 format on Cloudflare Workers:
#   openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in raw.pem -out app.pem
# Paste the *contents* of app.pem (including BEGIN/END lines) as GITHUB_APP_PRIVATE_KEY.
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_INSTALLATION_ID=
EOF
  echo "[bootstrap] Wrote $DEV_VARS"
fi

if [[ ! -f "$WEB_ENV" ]]; then
  mkdir -p "$(dirname "$WEB_ENV")"
  cat > "$WEB_ENV" <<EOF
# Web app dev environment — auto-generated by scripts/dev/bootstrap.sh.
# Do not commit this file.

NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=$NEXTAUTH_SECRET

CONTROL_PLANE_URL=http://localhost:8787
# Inlined into the client bundle at build time — must be present before \`npm run dev:web\`.
NEXT_PUBLIC_WS_URL=ws://localhost:8787

# Must match packages/control-plane/.dev.vars
INTERNAL_CALLBACK_SECRET=$INTERNAL_CALLBACK_SECRET

UNSAFE_ALLOW_ALL_USERS=true
NEXT_PUBLIC_SANDBOX_PROVIDER=local-docker
NEXT_PUBLIC_SCM_PROVIDER=github

# Only needed for cross-machine LAN access (e.g. running \`npm run dev:web:lan\`
# and browsing from another host on the LAN). Comma-separated list of origins
# Next.js will accept HMR / hydration requests from. Leave empty for localhost-only dev.
NEXT_DEV_ALLOWED_ORIGINS=

# Fill these from your dev GitHub OAuth App at https://github.com/settings/applications/new
#   Homepage URL:                http://localhost:3000
#   Authorization callback URL:  http://localhost:3000/api/auth/callback/github
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
EOF
  echo "[bootstrap] Wrote $WEB_ENV"
fi

cat <<'NEXT'

[bootstrap] Next steps:

  1. Create a GitHub OAuth App at https://github.com/settings/applications/new
       Homepage URL:                http://localhost:3000
       Authorization callback URL:  http://localhost:3000/api/auth/callback/github
     Paste Client ID / Secret into packages/web/.env.local.

  2. Create a GitHub App at https://github.com/settings/apps/new for repo cloning.
     Generate a private key, convert to PKCS#8:
       openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in raw.pem -out app.pem
     Paste GITHUB_APP_ID, contents of app.pem as GITHUB_APP_PRIVATE_KEY, and
     GITHUB_APP_INSTALLATION_ID into packages/control-plane/.dev.vars.

  3. Run:
       npm run dev:migrate
       npm run dev

NEXT
